#info:
#  component: Edge Server
spring:
  application:
    name: gateway-server
  zipkin:
    base-url: http://192.168.1.7:9411  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  prefix: /api
  routes:
    validation: 
      path: /validation/**
      serviceId: validation-service
    commercialAutoPolicy: 
      path: /commercialAutoPolicy/**
      serviceId: commercialAuto-policy-service          
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
      
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG