server:  
  port: ${PORT:3333}
spring:
  application:
    name: validation-service
  zipkin:
    base-url: http://192.168.1.7:9411  
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2   
    
feign:
  hystrix:
    enabled: false      
ribbon:
  eager-load:
  enabled: true
  clients: commercialAuto-service
  ConnectTimeout: 60000
  ReadTimeout: 60000          
  eureka:
    enabled: true